### PR TITLE
Support keyboard shortcuts.

### PR DESCRIPTION
**Pull request by aminroosta**
@ueokande  

This is a **raw** attempt at supporting [keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands).   
The good thing about them is that they work in any url (e.g `about:addons`).  

Screen Shot 2019-05-12 at 3 17 06 AM

### CODE REVIEW

**Comment by ueokande** [comment]
We can use json settings

**Comment by aminroosta** [comment]
No you can’t, these are global shortcuts... that work in any tab.  Even when the plugin is not loaded.

**Comment by aminroosta** [comment]
@ueokande

**Comment by ueokande** [comment]
@aminroosta 
Thank you for your proposal.

I have understood that the global keymaps has different characters from Vim Vixen's keymaps. 
But we need to resolve some problems by ths ways. The global keymaps is not flexible and user cannot configure all keymaps. Additionally that is independent on the JSON settings. That is confusing for users.

We need more disscussion about this features.

**Comment by ueokande** [comment]
I cannot now reopen this PR.  Did you remove your forked repository or branch?

Please open a new issues or PR.

**Comment by aminroosta** [comment]
Yeah, i think i removed the repo a few weeks ago.
I the changes are still visible in the "files changed" section of this PR.

I'll leave it to you if & when you wanted to implement keyboard shortcuts.

**Pull request closed without merging**
