### PR TITLE
Check scrollability by actually scrolling elements

### PR DESCRIPTION
**Pull request by femnad**
Addresses #825

When `findScrollable` yields no results, check if we can return the current `scrollingElement` instead, ignoring `doneScrolling` check this time. This fixes the behaviour when it's not possible to scroll up from the bottom of a page.

### CODE REVIEW

**Comment by sierratango88** [comment]
I have tested this commit on the following web pages:
1. https://en.wikipedia.org/wiki/Main_Page
1. https://music.youtube.com
1. https://github.com/enkore/j4-dmenu-desktop

It works on Wikipedia but, unfortunately, it does not work for the others.

Tested on Firefox 82.0b8.

**Comment by femnad** [comment]
Yeah, you're right, embarrassingly I've only tested on Hacker News. However, the behavior on those sites you've mentioned is similarly broken on master. So I propose changing the scrolling logic somewhat which has the downside of reintroducing #267 but fixes the scrolling on other sites. This could be applied as a temporary measure to fix the existing scrolling bug until there is another implementation which can address #267 without causing problems in other sites.

**Comment by femnad** [comment]
New proposal; when seeking scrollable elements, evaluate style checks first and then actually scroll (down and back up) the element to see if it can be scrolled. Credit for that approach goes to [Vimium](https://github.com/philc/vimium/blob/bdf654aebe6f570f427c5f7bc9592cad86e642b5/content_scripts/scroller.js).

Tested on:
* Hacker News
* Gmail
* Youtube Music
* Github repo pages
* Wikipedia main page

**Comment by sierratango88** [comment]
I can confirm it's working great on all those previously affected web pages with the latest commit. Excellent work @femnad!

**Review by ueokande — APPROVED** [review]
great!

**Comment by aminroosta** [comment]
Just saw this in the release notes.
Guys, you rock! Think you so much for keeping this the best vim plugin for firefox.

**Comment by apiraino** [comment]
thanks @femnad for fixing this up :)

**Pull request merged**
