### PR TITLE
Smooth scroll

### LINKED ISSUE #57: Smooth scrolling option
### I'm opening this issue because:

- [x] I'll propose a new feature

### Description

Scrolling by pages is abrupt. An option to smoothly scroll would be nice.

#### Steps to Reproduce

1. Scroll using a keybind
2. Movement is instantaneous.

#### System configuration

- Operating system: Linux
- Firefox version: 57
- Vim-Vixen version: 0.1

### PR DESCRIPTION
**Pull request by ueokande**
close #57 

It supports smooth scroll by property `smoothscroll`:

```vim
:set smoothscroll      " enable smooth scroll
:set nosmoothscroll    " disable smooth scroll
```

### CODE REVIEW

**Comment by codethief** [comment]
Could you elaborate on where/how one can set the `smoothscroll` property?

**Comment by Nefari0uss** [comment]
@codethief Unless I'm mistaken, you'd bring up the command window with `:` and type `set smoothscoll`.

**Comment by Lesik** [comment]
Maybe it's just me, but I find the this implementation impossible to use. The scrolling is smooth if you press the key once, but if you press it multiple times, or worse, hold it, it stutters horribly. Is everybody else not experiencing this or just not bothered by this?

**Comment by EnacheB** [comment]
@Lesik I agree with you, the arrow keys give much smoother scrolling

**Comment by ueokande** [comment]
@Lesik @EnacheB 
Yes, Vim-Vixen scrolls pages by controlling animation, itself.  Firefox's one can be better on performance than it.

**Comment by indeedwatson** [comment]
Is the stuttering going to get fixed? It doesn't seem "smooth" at all. How does vimium achieve its truly smooth scrolling?

**Comment by ueokande** [comment]
I added #425. Please continue to discuss in the issue.

**Pull request merged**
